version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5544:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    networks:
      - my_network
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: testdb
    networks:
      - my_network
networks:
  my_network: