import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

export const apiSlice = createApi({
    reducerPath: 'apiSlice',
    baseQuery: fetchBaseQuery({
        baseUrl: 'http://localhost:4001/',
    }),
    tagTypes: ['Post'],
    endpoints: (builder) => ({
        getPosts: builder.query({
            query: () => '/posts',
            providesTags: ['Post'],
        }),
        // addNewPost: builder.mutation({}),
        // updatePost: builder.mutation({}),
        deletePost: builder.mutation({
            query: (id) => ({
                url: `/posts/${id}`,
                method: 'DELETE',
                credentials: 'include'
            }),
            invalidatesTags: ['Post']
        })
    }),
})

// autogenerated hooks
export const {
    useGetPostsQuery,
    useDeletePostMutation
} = apiSlice